=== AnnaHomolka/PyWPS/pywps/processes/process_chain.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">

	<!-- Predefinition of inputs -->
	<xs:group name="processInputs">
		<xs:sequence>
			<xs:element name="input" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="localIdentifier" use="optional"/>
					<xs:attribute name="sourceIdentifier" use="optional"/>
					<xs:attribute name="identifier" use="required"/>
					<xs:attribute name="sourceProcess" use="optional"/>
					<xs:attribute name="sourceName" use="optional"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="output" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="identifier"/>
					<xs:attribute name="localIdentifier"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:attributeGroup name="processAttributes">
		<xs:attribute name="service" type="xs:string" use="required"/>
		<xs:attribute name="processID" type="xs:string" use="required"/>
		<xs:attribute name="identifier" type="xs:string" use="required"/>
		<xs:attribute name="synchron" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="True"/>
					<xs:enumeration value="False"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="sleepSecs" type="xs:int" use="optional"/>
	</xs:attributeGroup>
	
	<!-- Start of the description of the process chain -->
	<xs:element name="workflow">
		<xs:complexType>
			<xs:sequence>
				
				<!-- Description of the process inputs-->
				<xs:element name="inputs" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="input" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="title" type="xs:string" use="required"/>
									<xs:attribute name="type" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="complex"/>
												<xs:enumeration value="literal"/>
												<xs:enumeration value="boundingBox"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="localIdentifier" type="xs:string" use="optional"/>
									<xs:attribute name="defaultValue" type="xs:string" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<!-- Desciption of the processes which will be chained-->
				<xs:element name="try" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="startProcess" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:group ref="processInputs"/>
									</xs:sequence>
									<xs:attributeGroup ref="processAttributes"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="catch">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="startProcess" minOccurs="1" maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:group ref="processInputs"/>
												</xs:sequence>
												<xs:attributeGroup ref="processAttributes"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				
				<!-- Description of the outputs of the processs chain-->
				<xs:element name="outputs" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="output" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="sourceProcess" type="xs:string" use="optional"/>
									<xs:attribute name="sourceIdentifier" type="xs:string" use="optional"/>
									<xs:attribute name="localIdentifier" type="xs:string" use="optional"/>
									<xs:attribute name="type" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="complex"/>
												<xs:enumeration value="literal"/>
												<xs:enumeration value="boundingBox"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			
			</xs:sequence>
			<xs:attribute name="identifier" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== AnnaHomolka/PyWPS/tests/example.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workflow identifier="example"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="process_chain.xsd">
	<inputs>
		<input defaultValue="5" localIdentifier="Input1" title="first Input" type="literal"/>
		<input defaultValue="4" localIdentifier="Input2" title="second Input" type="literal"/>
		<input defaultValue="6" localIdentifier="Input3" title="third Input" type="literal"/>
	</inputs>
	<try>
		<startProcess service="http://localhost/cgi-bin/pywps.cgi" processID="dummyprocess_1" identifier="dummyprocess" synchron="False" sleepSecs="1">
			<input sourceIdentifier="Input1" identifier="i1"/>
			<input sourceIdentifier="Input2" identifier="i2"/>
			<input sourceIdentifier="Input3" identifier="i3"/>
			<output localIdentifier="x" identifier="output1"/>
		</startProcess>
		<catch>
			<startProcess service="http://localhost/cgi-bin/pywps.cgi" processID="dummyprocess_1" identifier="dummyprocess" synchron="False" sleepSecs="1">
				<input sourceIdentifier="Input1" identifier="i1"/>
				<input sourceIdentifier="Input2" identifier="i2"/>
				<input sourceIdentifier="Input3" identifier="i3"/>
				<output localIdentifier="x" identifier="output1"/>
			</startProcess>
		
		</catch>
	</try>
	
	<try>
		<startProcess service="http://localhost/cgi-bin/pywps.cgi" processID="dummyprocess_2" identifier="dummyprocess">
			<input sourceProcess="dummyprocess_1" sourceName="output1" identifier="i1"/>
			<input localIdentifier='x' identifier="i2"/>
			<input sourceProcess="dummyprocess_1" sourceName="output2" identifier="i3"/>
		</startProcess>
		<catch>
			<startProcess service="http://localhost/cgi-bin/pywps.cgi" processID="dummyprocess_2" identifier="dummyprocess">
				<input sourceProcess="dummyprocess_1" sourceName="output1" identifier="i1"/>
				<input localIdentifier='x' identifier="i2"/>
				<input sourceProcess="dummyprocess_1" sourceName="output2" identifier="i3"/>
			</startProcess>
		
		</catch>
	</try>
	
	<outputs>
		<output sourceProcess="dummyprocess_1" sourceIdentifier="output1" type="literal"/>
		<output sourceProcess="dummyprocess_2" sourceIdentifier="output2" type="literal"/>
		<output localIdentifier="x" type="literal"/>
	</outputs>
</workflow>
